FROM mkorenkov/alpine

RUN apk add --update bash \
                     curl \
                     git \
                     gcc \
                     g++ \
                     sqlite-dev \
                     sqlite-libs
